[package]
name = "asoby"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
cpal = "0.15"
crossterm = "0.29"
ctrlc = "3"
dirs = "5"
ureq = "3"
zip = "2"
image = { version = "0.25", default-features = false, features = ["png"] }
libc = "0.2"
libloading = "0.8"
ringbuf = "0.4"
tempfile = "3"
viuer = "0.11"
