name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  id-token: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            extension: .exe
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: .exe
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-infrastructure
      - run: yq -p=toml -o=toml -i '.package.version = ("${{ github.ref_name }}" | sub("^v"; ""))' Cargo.toml
      - run: cargo test
      - run: cargo build -r
      - run: mkdir release
      - run: cp target/release/asobou${{ matrix.extension }} release/asobou-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
      - uses: actions/upload-artifact@v7
        with:
          name: release-${{ matrix.target }}
          path: release/*
  publish-crates:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-infrastructure
      - run: yq -p=toml -o=toml -i '.package.version = ("${{ github.ref_name }}" | sub("^v"; ""))' Cargo.toml
      - run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-infrastructure
      - uses: actions/download-artifact@v8
        with:
          pattern: release-*
          path: release
          merge-multiple: true
      - run: yq -p=json -o=json -i '.version = ("${{ github.ref_name }}" | sub("^v"; "")) | .optionalDependencies[] = ("${{ github.ref_name }}" | sub("^v"; ""))' npm/asobou/package.json
      - run: cp "release/asobou-${{ github.ref_name }}-x86_64-apple-darwin" npm/asobou-darwin-x64/asobou
      - run: cp "release/asobou-${{ github.ref_name }}-aarch64-apple-darwin" npm/asobou-darwin-arm64/asobou
      - run: cp "release/asobou-${{ github.ref_name }}-aarch64-unknown-linux-gnu" npm/asobou-linux-arm64-gnu/asobou
      - run: cp "release/asobou-${{ github.ref_name }}-x86_64-unknown-linux-gnu" npm/asobou-linux-x64-gnu/asobou
      - run: |
          for package in npm/asobou-*; do
            (
              cp readme.md "$package"
              cp license "$package"
              cd "$package"
              yq -p=json -o=json -i '.version = ("${{ github.ref_name }}" | sub("^v"; ""))' package.json
              chmod +x asobou*
              npm publish
            )
          done
      - run: cp readme.md npm/asobou
      - run: cp license npm/asobou
      - run: npm publish
        working-directory: npm/asobou
  release:
    needs:
      - publish-crates
      - publish-npm
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: release-*
          path: release
          merge-multiple: true
      - run: shasum -a 256 * > SHA256SUMS
        working-directory: release
      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
