name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-15-intel
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: '.exe'

    steps:
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libasound2-dev pkg-config
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          mise_toml: |
            [tools]
            rust = 'latest'
            yq = 'latest'
      - run: yq -p=toml -o=toml -i '.package.version = ("${{ github.ref_name }}" | sub("^v"; ""))' Cargo.toml
      - run: cargo test
      - run: cargo build -r
      - run: mkdir release
      - run: cp target/release/asoby${{ matrix.extension }} release/asoby-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
      - uses: actions/upload-artifact@v7
        with:
          name: release-${{ matrix.target }}
          path: 'release/*'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: release-*
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            'release/*'