name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**/*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**/*"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - macos-15-intel
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
          - windows-11-arm
          - windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-infrastructure
      - run: cargo test
      - run: cargo build -r
